export const FETCH_GOODS = "MAIN/FETCH_GOODS";
export const EXTENDED_STATE = "MAIN/EXTENDED_STATE";
export const ADD_TO_CART = "MAIN/ADD_TO_CART";
export const DELETE_FROM_CART = "MAIN/DELETE_FROM_CART";
export const CHANGE_CATEGORY = "MAIN/CHANGE_CATEGORY";
export const CLEAR_CART = "MAIN/CLEAR_CART";
export const FETCH_CATALOG_GOODS = "MAIN/FETCH_CATALOG_GOODS";
